export const demoPassage = {
  id: 'water_cycle_1',
  concept: 'The Water Cycle',
  semanticUnits: [
    {
      id: 'u1',
      baseMeaning: 'Sunlight warms water, causing it to evaporate.',
      variants: {
        beginner: 'Warm sunlight shines on rivers, lakes, and soil. The water rises into the air.',
        intermediate: 'Warm sunlight lifts water from rivers, lakes, and soil into the air.',
        advanced: 'Solar energy drives evaporation from rivers, lakes, and soil into the air.',
      },
      flaggedTerms: ['sunlight', 'evaporate', 'water'],
      wordDefs: {
        sunlight: { meaning: 'Light and heat from the sun', related: ['water', 'warm'] },
        evaporate: { meaning: 'When liquid water turns into invisible vapor and rises', related: ['water', 'air'] },
        water: { meaning: 'A clear liquid that plants and animals need to live', related: [] },
      },
    },
    {
      id: 'u2',
      baseMeaning: 'The water vapor rises and cools as it goes higher in the atmosphere.',
      variants: {
        beginner: 'The water vapor goes up and gets cooler as it rises high in the air.',
        intermediate: 'Water vapor rises high into the atmosphere and gradually cools.',
        advanced: 'Ascending water vapor cools in the upper atmosphere through adiabatic expansion.',
      },
      flaggedTerms: ['vapor', 'rises', 'cools', 'atmosphere'],
      wordDefs: {
        vapor: { meaning: 'Water that has turned into an invisible gas', related: ['water', 'air', 'rises'] },
        atmosphere: { meaning: 'All the air surrounding Earth', related: ['air', 'sky'] },
      },
    },
    {
      id: 'u3',
      baseMeaning: 'As the vapor cools, it condenses into tiny water droplets.',
      variants: {
        beginner: 'When the water vapor gets cold enough, it turns into tiny drops of water.',
        intermediate: 'The cooling vapor condenses into microscopic water droplets.',
        advanced: 'Vapor undergoes condensation, transitioning to liquid water droplets.',
      },
      flaggedTerms: ['condenses', 'droplets', 'cooling'],
      wordDefs: {
        condenses: { meaning: 'When a gas turns into a liquid, usually because it gets cold', related: ['vapor', 'drops'] },
        droplets: { meaning: 'Tiny drops of liquid water', related: ['water', 'clouds'] },
      },
    },
    {
      id: 'u4',
      baseMeaning: 'Millions of these droplets gather together to form clouds.',
      variants: {
        beginner: 'Millions of tiny drops stick together and make clouds in the sky.',
        intermediate: 'Billions of these tiny droplets collect together to form visible clouds.',
        advanced: 'Aggregated water droplets form visible cloud formations across the troposphere.',
      },
      flaggedTerms: ['droplets', 'gather', 'clouds'],
      wordDefs: {
        clouds: { meaning: 'A visible mass of water droplets floating in the air', related: ['water', 'sky', 'droplets'] },
      },
    },
    {
      id: 'u5',
      baseMeaning: 'When droplets become too heavy, they fall as rain or snow.',
      variants: {
        beginner: 'When the water drops get too heavy, they fall back to Earth as rain or snow.',
        intermediate: 'When droplets accumulate and become too heavy to float, they fall as precipitation.',
        advanced: 'Coalescence increases droplet mass until gravitational forces induce precipitation.',
      },
      flaggedTerms: ['droplets', 'heavy', 'precipitation', 'rain'],
      wordDefs: {
        precipitation: { meaning: 'Water that falls from clouds, like rain, snow, or sleet', related: ['rain', 'clouds'] },
        rain: { meaning: 'Water falling from clouds in liquid form', related: ['water', 'droplets'] },
      },
    },
    {
      id: 'u6',
      baseMeaning: 'The water returns to rivers, lakes, and soil, and the cycle continues.',
      variants: {
        beginner: 'The water flows back into rivers and lakes, or soaks into the ground. Then it all starts again.',
        intermediate: 'Water returns to rivers, lakes, and soil, where the cycle begins anew.',
        advanced: 'Returned water percolates into soil aquifers or flows to reservoirs, enabling cyclical continuation.',
      },
      flaggedTerms: ['cycle', 'returns'],
      wordDefs: {
        cycle: { meaning: 'A process that repeats again and again', related: ['continues', 'water'] },
      },
    },
  ],
};

export const definitions = {
  sunlight: { word: 'sunlight', meaning: 'Light and heat from the sun', example: 'Sunlight warms the water.' },
  evaporate: { word: 'evaporate', meaning: 'To turn from liquid into vapor; to rise into the air', example: 'Water evaporates on warm days.' },
  water: { word: 'water', meaning: 'A clear liquid found in oceans, rivers, and lakes', example: 'We drink water every day.' },
  vapor: { word: 'vapor', meaning: 'Water in the form of an invisible gas in the air', example: 'Steam is water vapor.' },
  atmosphere: { word: 'atmosphere', meaning: 'All the air that surrounds Earth', example: 'Clouds float in the atmosphere.' },
  condense: { word: 'condense', meaning: 'To change from a gas into a liquid', example: 'Water vapor condenses on cold surfaces.' },
  droplets: { word: 'droplets', meaning: 'Very small drops of liquid', example: 'Clouds are made of tiny water droplets.' },
  clouds: { word: 'clouds', meaning: 'Visible masses of water droplets floating in the sky', example: 'Dark clouds bring rain.' },
  precipitation: { word: 'precipitation', meaning: 'Water that falls from clouds as rain, snow, or sleet', example: 'We got two inches of precipitation last week.' },
  rain: { word: 'rain', meaning: 'Water falling from clouds in liquid form', example: 'The rain watered the plants.' },
  cycle: { word: 'cycle', meaning: 'A series of events that repeat over and over', example: 'The water cycle never stops.' },
  gravity: { word: 'gravity', meaning: 'The force that pulls things down toward Earth', example: 'Gravity pulls raindrops to the ground.' },
};

export const karaokeDemoD = {
  title: 'Biology Demo (D)',
  lines: [
    'Biology studies living organisms and their interactions.',
    'It explains structures functions and processes.',
    'Life depends on systems and it evolves over time.',
  ],
  wordData: {
    biology: { meaning: 'The scientific study of living things.', related: ['organisms', 'life', 'systems'] },
    studies: { meaning: 'Examines something carefully to understand it.', related: ['biology', 'explains'] },
    living: { meaning: 'Having life and biological activity.', related: ['organisms', 'life'] },
    organisms: { meaning: 'Individual living things such as plants, animals, and microbes.', related: ['living', 'life'] },
    and: { meaning: 'A connector that joins ideas or words together.', related: [] },
    their: { meaning: 'Belonging to those things mentioned earlier.', related: ['organisms'] },
    interactions: { meaning: 'Ways things affect each other.', related: ['organisms', 'systems'] },
    it: { meaning: 'A pronoun referring to a previously mentioned idea.', related: ['biology', 'life', 'systems'], referential: 'Refers to the nearest previous main concept in context.' },
    explains: { meaning: 'Makes an idea clear and understandable.', related: ['studies', 'processes'] },
    structures: { meaning: 'How parts are arranged or organized.', related: ['organisms', 'systems'] },
    functions: { meaning: 'Jobs or roles that parts perform.', related: ['structures', 'processes'] },
    processes: { meaning: 'Series of actions or changes over time.', related: ['functions', 'evolves'] },
    life: { meaning: 'The condition of being alive.', related: ['living', 'organisms'] },
    depends: { meaning: 'Needs something else in order to work or continue.', related: ['systems', 'life'] },
    on: { meaning: 'Shows connection or reliance.', related: [] },
    systems: { meaning: 'Sets of connected parts working together.', related: ['structures', 'functions', 'interactions'] },
    evolves: { meaning: 'Changes gradually over time.', related: ['processes', 'time'] },
    over: { meaning: 'Across a period of time.', related: ['time'] },
    time: { meaning: 'Continuous flow in which change happens.', related: ['evolves', 'processes'] },
  },
};

export const readingKaraokePassage = {
  title: 'Water Cycle Guided Reading',
  lines: [
    'Warm sunlight lifts water from rivers lakes and soil into the air.',
    'The water becomes vapor and cooler air helps it condense into clouds.',
    'Moving winds carry the clouds until tiny droplets gather and grow heavy.',
    'Rain falls back to the surface where plants absorb the water.',
    'Streams carry it onward and the cycle repeats through seasons.',
    'This repeating pattern helps ecosystems stay balanced over time.',
  ],
  wordData: {
    warm: { meaning: 'Having a comfortably high temperature.', related: ['sunlight', 'water'] },
    sunlight: { meaning: 'Light and heat coming from the sun.', related: ['warm', 'water'] },
    lifts: { meaning: 'Raises something upward.', related: ['water', 'air'] },
    water: { meaning: 'A clear liquid essential for life.', related: ['vapor', 'rain', 'droplets'] },
    from: { meaning: 'Shows a starting point.', related: [] },
    rivers: { meaning: 'Natural flowing channels of water.', related: ['streams', 'water'] },
    lakes: { meaning: 'Large inland bodies of still water.', related: ['water', 'rivers'] },
    and: { meaning: 'A connector that joins ideas or words together.', related: [] },
    soil: { meaning: 'The upper layer of earth where plants grow.', related: ['plants', 'water'] },
    into: { meaning: 'Moving to the inside of something.', related: [] },
    the: { meaning: 'A word that points to a specific noun.', related: [] },
    air: { meaning: 'The invisible mixture of gases around us.', related: ['vapor', 'clouds'] },
    becomes: { meaning: 'Changes into a new state.', related: ['water', 'vapor'] },
    vapor: { meaning: 'Water in gas form.', related: ['water', 'condense'] },
    cooler: { meaning: 'Lower in temperature.', related: ['condense', 'air'] },
    helps: { meaning: 'Makes an action easier to happen.', related: ['condense'] },
    it: { meaning: 'A pronoun referring to a previously mentioned thing.', related: ['water', 'vapor', 'cycle'], referential: 'Refers to the nearest previous key concept (usually water or cycle).' },
    condense: { meaning: 'To change from gas into liquid.', related: ['vapor', 'droplets'] },
    clouds: { meaning: 'Visible groups of tiny water droplets in the sky.', related: ['droplets', 'rain'] },
    moving: { meaning: 'Changing position over time.', related: ['winds', 'carry'] },
    winds: { meaning: 'Natural movement of air.', related: ['carry', 'clouds'] },
    carry: { meaning: 'Transport from one place to another.', related: ['winds', 'streams'] },
    until: { meaning: 'Up to the point when something happens.', related: [] },
    tiny: { meaning: 'Very small in size.', related: ['droplets'] },
    droplets: { meaning: 'Small drops of liquid water.', related: ['clouds', 'rain'] },
    gather: { meaning: 'Come together in one place.', related: ['droplets', 'clouds'] },
    grow: { meaning: 'Become larger or greater.', related: ['heavy'] },
    heavy: { meaning: 'Having a lot of weight.', related: ['rain', 'droplets'] },
    rain: { meaning: 'Liquid water that falls from clouds.', related: ['clouds', 'water'] },
    falls: { meaning: 'Moves downward due to gravity.', related: ['rain'] },
    back: { meaning: 'Returning to a previous place.', related: ['surface'] },
    to: { meaning: 'Shows direction toward something.', related: [] },
    surface: { meaning: 'The outer top layer of something.', related: ['soil', 'plants'] },
    where: { meaning: 'Refers to a place.', related: [] },
    plants: { meaning: 'Living organisms that make their own food from sunlight.', related: ['soil', 'water'] },
    absorb: { meaning: 'Take in or soak up.', related: ['plants', 'water'] },
    streams: { meaning: 'Small flowing bodies of water.', related: ['rivers', 'carry'] },
    onward: { meaning: 'Forward to the next stage.', related: ['cycle'] },
    cycle: { meaning: 'A sequence that repeats.', related: ['repeats', 'water'] },
    repeats: { meaning: 'Happens again and again.', related: ['cycle', 'pattern'] },
    through: { meaning: 'From one side to another or across duration.', related: [] },
    seasons: { meaning: 'Parts of the year with different weather patterns.', related: ['time'] },
    this: { meaning: 'Points to an idea just mentioned.', related: ['pattern', 'cycle'], referential: 'Refers to the water cycle process described in prior lines.' },
    repeating: { meaning: 'Occurring again in the same way.', related: ['pattern', 'cycle'] },
    pattern: { meaning: 'A repeated arrangement or sequence.', related: ['repeats', 'cycle'] },
    ecosystems: { meaning: 'Communities of living things and their environment.', related: ['balanced', 'plants'] },
    stay: { meaning: 'Continue in the same condition.', related: ['balanced'] },
    balanced: { meaning: 'Kept stable and in healthy proportion.', related: ['ecosystems'] },
    over: { meaning: 'Across a period of time.', related: ['time'] },
    time: { meaning: 'The ongoing sequence in which events occur.', related: ['seasons', 'cycle'] },
  },
};

export const writingDemos = {
  A: {
    topic: 'Water Cycle',
    essay: 'The water cycle begins when sunlight warms lakes, rivers, and soil. Liquid water then evaporates into invisible vapor that rises through the air. As the vapor climbs higher, cooler temperatures cause condensation. Tiny droplets gather together and form clouds across the sky. Winds transport the clouds over land and sea in repeating patterns. When droplets become heavy, precipitation falls as rain, snow, or sleet. Some water infiltrates the soil and replenishes underground aquifers. Other water becomes runoff and flows into streams and rivers. Plants absorb moisture and release part of it back through transpiration. This continuous circulation supports ecosystems, agriculture, and human communities.',
    advancedSuggestions: [
      'Use a contrastive opener such as “Although the cycle seems simple, its feedback loops are remarkably dynamic.”',
      'Introduce causal connectors like “consequently” and “therefore” to strengthen logical flow.',
      'Add a synthesis sentence linking atmospheric physics with ecological outcomes.',
    ],
    wordInsights: {
      evaporates: { definition: 'Changes from liquid into gas.', struggledCount: 24, contributors: ['liquid', 'vapor', 'rises'], difficulty: 1 },
      condensation: { definition: 'The process where water vapor cools into liquid droplets.', struggledCount: 31, contributors: ['vapor', 'cooler', 'droplets'], difficulty: 1 },
      precipitation: { definition: 'Water that falls from clouds as rain, snow, or sleet.', struggledCount: 29, contributors: ['rain', 'snow', 'sleet'], difficulty: 1 },
      infiltrates: { definition: 'Moves gradually into a material, especially soil.', struggledCount: 42, contributors: ['soil', 'underground', 'aquifers'], difficulty: 2 },
      aquifers: { definition: 'Underground layers of rock or sediment that store water.', struggledCount: 44, contributors: ['underground', 'replenishes', 'water'], difficulty: 2 },
      runoff: { definition: 'Water that flows over land into rivers and streams.', struggledCount: 21, contributors: ['flows', 'streams', 'rivers'], difficulty: 2 },
      transpiration: { definition: 'The release of water vapor from plants into the air.', struggledCount: 53, contributors: ['plants', 'moisture', 'air'], difficulty: 3 },
      circulation: { definition: 'Continuous movement in a repeating path.', struggledCount: 26, contributors: ['continuous', 'repeating', 'supports'], difficulty: 2 },
      ecosystems: { definition: 'Communities of organisms interacting with their environment.', struggledCount: 34, contributors: ['supports', 'agriculture', 'communities'], difficulty: 3 },
    },
  },
  B: {
    topic: 'Algorithms in Daily Life',
    essay: 'An algorithm is a step-by-step method for solving a problem. Every morning, navigation apps calculate routes from traffic data. The software analyzes congestion and predicts travel time for each road. It then optimizes the path to reduce delays and fuel use. Recommendation systems rank movies, songs, and products from user behavior. These systems personalize choices by detecting patterns in large datasets. Behind the screen, models update continuously as new information arrives. Engineers test accuracy, fairness, and reliability before deployment. Even simple household devices now use embedded logic to automate tasks. Understanding algorithms helps people evaluate digital tools with critical thinking.',
    advancedSuggestions: [
      'Frame the essay with a provocative claim about hidden algorithmic governance in ordinary routines.',
      'Use precise verbs like “prioritize,” “infer,” and “calibrate” to increase rhetorical sophistication.',
      'Close with a nuanced caveat about transparency, bias, and accountability.',
    ],
    wordInsights: {
      algorithm: { definition: 'A precise sequence of instructions to solve a task.', struggledCount: 28, contributors: ['step-by-step', 'method', 'solving'], difficulty: 1 },
      analyzes: { definition: 'Examines details to understand structure or meaning.', struggledCount: 22, contributors: ['traffic', 'predicts', 'data'], difficulty: 1 },
      congestion: { definition: 'A crowded condition that slows movement.', struggledCount: 25, contributors: ['traffic', 'delays', 'road'], difficulty: 2 },
      optimizes: { definition: 'Makes something as effective or efficient as possible.', struggledCount: 39, contributors: ['reduce', 'delays', 'fuel'], difficulty: 2 },
      recommendation: { definition: 'A suggested option generated from relevant information.', struggledCount: 19, contributors: ['rank', 'movies', 'products'], difficulty: 1 },
      personalize: { definition: 'Tailor content to individual preferences.', struggledCount: 33, contributors: ['choices', 'user', 'patterns'], difficulty: 2 },
      datasets: { definition: 'Organized collections of data used for analysis.', struggledCount: 37, contributors: ['patterns', 'information', 'models'], difficulty: 2 },
      deployment: { definition: 'The stage where a system is released for real use.', struggledCount: 41, contributors: ['engineers', 'test', 'reliability'], difficulty: 3 },
      embedded: { definition: 'Built into a larger device or system.', struggledCount: 27, contributors: ['devices', 'logic', 'automate'], difficulty: 2 },
      accountability: { definition: 'Responsibility for decisions and their consequences.', struggledCount: 48, contributors: ['critical', 'evaluate', 'tools'], difficulty: 3 },
    },
  },
  C: {
    topic: 'Cognitive Science and Learning',
    essay: 'Cognitive science explores how the mind processes information. Researchers combine psychology, neuroscience, linguistics, and computer science. Attention acts like a filter that selects important signals. Working memory temporarily holds ideas while people solve problems. Repetition strengthens neural pathways and supports long-term retention. Meaningful context helps learners connect new concepts to prior knowledge. Metacognition allows students to monitor and adjust their strategies. Sleep consolidates memories and improves later recall performance. Collaborative discussion can refine understanding through explanation and feedback. By studying these mechanisms, educators design instruction that improves comprehension.',
    advancedSuggestions: [
      'Introduce an analogy comparing attention to computational bandwidth to sharpen conceptual framing.',
      'Use disciplinary bridging phrases such as “from a neurocognitive perspective” for academic tone.',
      'Conclude with an implication sentence connecting theory to classroom intervention design.',
    ],
    wordInsights: {
      cognitive: { definition: 'Related to thinking, knowing, and understanding.', struggledCount: 23, contributors: ['mind', 'processes', 'information'], difficulty: 1 },
      neuroscience: { definition: 'The scientific study of the brain and nervous system.', struggledCount: 36, contributors: ['researchers', 'brain', 'science'], difficulty: 2 },
      linguistics: { definition: 'The scientific study of language.', struggledCount: 30, contributors: ['combine', 'language', 'researchers'], difficulty: 2 },
      attention: { definition: 'Focused mental effort on selected information.', struggledCount: 17, contributors: ['filter', 'important', 'signals'], difficulty: 1 },
      retention: { definition: 'The ability to keep information over time.', struggledCount: 28, contributors: ['repetition', 'long-term', 'memory'], difficulty: 2 },
      metacognition: { definition: 'Awareness and control of one’s own thinking process.', struggledCount: 49, contributors: ['monitor', 'adjust', 'strategies'], difficulty: 3 },
      consolidates: { definition: 'Stabilizes and strengthens something after learning.', struggledCount: 38, contributors: ['sleep', 'memories', 'recall'], difficulty: 2 },
      collaborative: { definition: 'Involving people working together.', struggledCount: 24, contributors: ['discussion', 'feedback', 'understanding'], difficulty: 1 },
      mechanisms: { definition: 'Underlying processes that make something work.', struggledCount: 35, contributors: ['studying', 'design', 'instruction'], difficulty: 2 },
      comprehension: { definition: 'The ability to understand meaning clearly.', struggledCount: 32, contributors: ['instruction', 'improves', 'understanding'], difficulty: 1 },
    },
  },
};
