export const demoPassage = {
  id: 'water_cycle_1',
  concept: 'The Water Cycle',
  semanticUnits: [
    {
      id: 'u1',
      baseMeaning: 'Sunlight warms water, causing it to evaporate.',
      variants: {
        beginner: 'Warm sunlight shines on rivers, lakes, and soil. The water rises into the air.',
        intermediate: 'Warm sunlight lifts water from rivers, lakes, and soil into the air.',
        advanced: 'Solar energy drives evaporation from rivers, lakes, and soil into the air.',
      },
      flaggedTerms: ['sunlight', 'evaporate', 'water'],
      wordDefs: {
        sunlight: { meaning: 'Light and heat from the sun', related: ['water', 'warm'] },
        evaporate: { meaning: 'When liquid water turns into invisible vapor and rises', related: ['water', 'air'] },
        water: { meaning: 'A clear liquid that plants and animals need to live', related: [] },
      },
    },
    {
      id: 'u2',
      baseMeaning: 'The water vapor rises and cools as it goes higher in the atmosphere.',
      variants: {
        beginner: 'The water vapor goes up and gets cooler as it rises high in the air.',
        intermediate: 'Water vapor rises high into the atmosphere and gradually cools.',
        advanced: 'Ascending water vapor cools in the upper atmosphere through adiabatic expansion.',
      },
      flaggedTerms: ['vapor', 'rises', 'cools', 'atmosphere'],
      wordDefs: {
        vapor: { meaning: 'Water that has turned into an invisible gas', related: ['water', 'air', 'rises'] },
        atmosphere: { meaning: 'All the air surrounding Earth', related: ['air', 'sky'] },
      },
    },
    {
      id: 'u3',
      baseMeaning: 'As the vapor cools, it condenses into tiny water droplets.',
      variants: {
        beginner: 'When the water vapor gets cold enough, it turns into tiny drops of water.',
        intermediate: 'The cooling vapor condenses into microscopic water droplets.',
        advanced: 'Vapor undergoes condensation, transitioning to liquid water droplets.',
      },
      flaggedTerms: ['condenses', 'droplets', 'cooling'],
      wordDefs: {
        condenses: { meaning: 'When a gas turns into a liquid, usually because it gets cold', related: ['vapor', 'drops'] },
        droplets: { meaning: 'Tiny drops of liquid water', related: ['water', 'clouds'] },
      },
    },
    {
      id: 'u4',
      baseMeaning: 'Millions of these droplets gather together to form clouds.',
      variants: {
        beginner: 'Millions of tiny drops stick together and make clouds in the sky.',
        intermediate: 'Billions of these tiny droplets collect together to form visible clouds.',
        advanced: 'Aggregated water droplets form visible cloud formations across the troposphere.',
      },
      flaggedTerms: ['droplets', 'gather', 'clouds'],
      wordDefs: {
        clouds: { meaning: 'A visible mass of water droplets floating in the air', related: ['water', 'sky', 'droplets'] },
      },
    },
    {
      id: 'u5',
      baseMeaning: 'When droplets become too heavy, they fall as rain or snow.',
      variants: {
        beginner: 'When the water drops get too heavy, they fall back to Earth as rain or snow.',
        intermediate: 'When droplets accumulate and become too heavy to float, they fall as precipitation.',
        advanced: 'Coalescence increases droplet mass until gravitational forces induce precipitation.',
      },
      flaggedTerms: ['droplets', 'heavy', 'precipitation', 'rain'],
      wordDefs: {
        precipitation: { meaning: 'Water that falls from clouds, like rain, snow, or sleet', related: ['rain', 'clouds'] },
        rain: { meaning: 'Water falling from clouds in liquid form', related: ['water', 'droplets'] },
      },
    },
    {
      id: 'u6',
      baseMeaning: 'The water returns to rivers, lakes, and soil, and the cycle continues.',
      variants: {
        beginner: 'The water flows back into rivers and lakes, or soaks into the ground. Then it all starts again.',
        intermediate: 'Water returns to rivers, lakes, and soil, where the cycle begins anew.',
        advanced: 'Returned water percolates into soil aquifers or flows to reservoirs, enabling cyclical continuation.',
      },
      flaggedTerms: ['cycle', 'returns'],
      wordDefs: {
        cycle: { meaning: 'A process that repeats again and again', related: ['continues', 'water'] },
      },
    },
  ],
};

export const definitions = {
  sunlight: { word: 'sunlight', meaning: 'Light and heat from the sun', example: 'Sunlight warms the water.' },
  evaporate: { word: 'evaporate', meaning: 'To turn from liquid into vapor; to rise into the air', example: 'Water evaporates on warm days.' },
  water: { word: 'water', meaning: 'A clear liquid found in oceans, rivers, and lakes', example: 'We drink water every day.' },
  vapor: { word: 'vapor', meaning: 'Water in the form of an invisible gas in the air', example: 'Steam is water vapor.' },
  atmosphere: { word: 'atmosphere', meaning: 'All the air that surrounds Earth', example: 'Clouds float in the atmosphere.' },
  condense: { word: 'condense', meaning: 'To change from a gas into a liquid', example: 'Water vapor condenses on cold surfaces.' },
  droplets: { word: 'droplets', meaning: 'Very small drops of liquid', example: 'Clouds are made of tiny water droplets.' },
  clouds: { word: 'clouds', meaning: 'Visible masses of water droplets floating in the sky', example: 'Dark clouds bring rain.' },
  precipitation: { word: 'precipitation', meaning: 'Water that falls from clouds as rain, snow, or sleet', example: 'We got two inches of precipitation last week.' },
  rain: { word: 'rain', meaning: 'Water falling from clouds in liquid form', example: 'The rain watered the plants.' },
  cycle: { word: 'cycle', meaning: 'A series of events that repeat over and over', example: 'The water cycle never stops.' },
  gravity: { word: 'gravity', meaning: 'The force that pulls things down toward Earth', example: 'Gravity pulls raindrops to the ground.' },
};

export const karaokeDemoD = {
  title: 'Biology Demo (D)',
  lines: [
    'Biology studies living organisms and their interactions.',
    'It explains structures functions and processes.',
    'Life depends on systems and it evolves over time.',
  ],
  wordData: {
    biology: { meaning: 'The scientific study of living things.', related: ['organisms', 'life', 'systems'] },
    studies: { meaning: 'Examines something carefully to understand it.', related: ['biology', 'explains'] },
    living: { meaning: 'Having life and biological activity.', related: ['organisms', 'life'] },
    organisms: { meaning: 'Individual living things such as plants, animals, and microbes.', related: ['living', 'life'] },
    and: { meaning: 'A connector that joins ideas or words together.', related: [] },
    their: { meaning: 'Belonging to those things mentioned earlier.', related: ['organisms'] },
    interactions: { meaning: 'Ways things affect each other.', related: ['organisms', 'systems'] },
    it: { meaning: 'A pronoun referring to a previously mentioned idea.', related: ['biology', 'life', 'systems'], referential: 'Refers to the nearest previous main concept in context.' },
    explains: { meaning: 'Makes an idea clear and understandable.', related: ['studies', 'processes'] },
    structures: { meaning: 'How parts are arranged or organized.', related: ['organisms', 'systems'] },
    functions: { meaning: 'Jobs or roles that parts perform.', related: ['structures', 'processes'] },
    processes: { meaning: 'Series of actions or changes over time.', related: ['functions', 'evolves'] },
    life: { meaning: 'The condition of being alive.', related: ['living', 'organisms'] },
    depends: { meaning: 'Needs something else in order to work or continue.', related: ['systems', 'life'] },
    on: { meaning: 'Shows connection or reliance.', related: [] },
    systems: { meaning: 'Sets of connected parts working together.', related: ['structures', 'functions', 'interactions'] },
    evolves: { meaning: 'Changes gradually over time.', related: ['processes', 'time'] },
    over: { meaning: 'Across a period of time.', related: ['time'] },
    time: { meaning: 'Continuous flow in which change happens.', related: ['evolves', 'processes'] },
  },
};

export const readingKaraokePassage = {
  title: 'Water Cycle Guided Reading',
  lines: [
    'Warm sunlight lifts water from rivers lakes and soil into the air.',
    'The water becomes vapor and cooler air helps it condense into clouds.',
    'Moving winds carry the clouds until tiny droplets gather and grow heavy.',
    'Rain falls back to the surface where plants absorb the water.',
    'Streams carry it onward and the cycle repeats through seasons.',
    'This repeating pattern helps ecosystems stay balanced over time.',
  ],
  wordData: {
    warm: { meaning: 'Having a comfortably high temperature.', related: ['sunlight', 'water'] },
    sunlight: { meaning: 'Light and heat coming from the sun.', related: ['warm', 'water'] },
    lifts: { meaning: 'Raises something upward.', related: ['water', 'air'] },
    water: { meaning: 'A clear liquid essential for life.', related: ['vapor', 'rain', 'droplets'] },
    from: { meaning: 'Shows a starting point.', related: [] },
    rivers: { meaning: 'Natural flowing channels of water.', related: ['streams', 'water'] },
    lakes: { meaning: 'Large inland bodies of still water.', related: ['water', 'rivers'] },
    and: { meaning: 'A connector that joins ideas or words together.', related: [] },
    soil: { meaning: 'The upper layer of earth where plants grow.', related: ['plants', 'water'] },
    into: { meaning: 'Moving to the inside of something.', related: [] },
    the: { meaning: 'A word that points to a specific noun.', related: [] },
    air: { meaning: 'The invisible mixture of gases around us.', related: ['vapor', 'clouds'] },
    becomes: { meaning: 'Changes into a new state.', related: ['water', 'vapor'] },
    vapor: { meaning: 'Water in gas form.', related: ['water', 'condense'] },
    cooler: { meaning: 'Lower in temperature.', related: ['condense', 'air'] },
    helps: { meaning: 'Makes an action easier to happen.', related: ['condense'] },
    it: { meaning: 'A pronoun referring to a previously mentioned thing.', related: ['water', 'vapor', 'cycle'], referential: 'Refers to the nearest previous key concept (usually water or cycle).' },
    condense: { meaning: 'To change from gas into liquid.', related: ['vapor', 'droplets'] },
    clouds: { meaning: 'Visible groups of tiny water droplets in the sky.', related: ['droplets', 'rain'] },
    moving: { meaning: 'Changing position over time.', related: ['winds', 'carry'] },
    winds: { meaning: 'Natural movement of air.', related: ['carry', 'clouds'] },
    carry: { meaning: 'Transport from one place to another.', related: ['winds', 'streams'] },
    until: { meaning: 'Up to the point when something happens.', related: [] },
    tiny: { meaning: 'Very small in size.', related: ['droplets'] },
    droplets: { meaning: 'Small drops of liquid water.', related: ['clouds', 'rain'] },
    gather: { meaning: 'Come together in one place.', related: ['droplets', 'clouds'] },
    grow: { meaning: 'Become larger or greater.', related: ['heavy'] },
    heavy: { meaning: 'Having a lot of weight.', related: ['rain', 'droplets'] },
    rain: { meaning: 'Liquid water that falls from clouds.', related: ['clouds', 'water'] },
    falls: { meaning: 'Moves downward due to gravity.', related: ['rain'] },
    back: { meaning: 'Returning to a previous place.', related: ['surface'] },
    to: { meaning: 'Shows direction toward something.', related: [] },
    surface: { meaning: 'The outer top layer of something.', related: ['soil', 'plants'] },
    where: { meaning: 'Refers to a place.', related: [] },
    plants: { meaning: 'Living organisms that make their own food from sunlight.', related: ['soil', 'water'] },
    absorb: { meaning: 'Take in or soak up.', related: ['plants', 'water'] },
    streams: { meaning: 'Small flowing bodies of water.', related: ['rivers', 'carry'] },
    onward: { meaning: 'Forward to the next stage.', related: ['cycle'] },
    cycle: { meaning: 'A sequence that repeats.', related: ['repeats', 'water'] },
    repeats: { meaning: 'Happens again and again.', related: ['cycle', 'pattern'] },
    through: { meaning: 'From one side to another or across duration.', related: [] },
    seasons: { meaning: 'Parts of the year with different weather patterns.', related: ['time'] },
    this: { meaning: 'Points to an idea just mentioned.', related: ['pattern', 'cycle'], referential: 'Refers to the water cycle process described in prior lines.' },
    repeating: { meaning: 'Occurring again in the same way.', related: ['pattern', 'cycle'] },
    pattern: { meaning: 'A repeated arrangement or sequence.', related: ['repeats', 'cycle'] },
    ecosystems: { meaning: 'Communities of living things and their environment.', related: ['balanced', 'plants'] },
    stay: { meaning: 'Continue in the same condition.', related: ['balanced'] },
    balanced: { meaning: 'Kept stable and in healthy proportion.', related: ['ecosystems'] },
    over: { meaning: 'Across a period of time.', related: ['time'] },
    time: { meaning: 'The ongoing sequence in which events occur.', related: ['seasons', 'cycle'] },
  },
};
